version: '3.8'
services:
  mongo:
    image: mongo:7.0
    container_name: mongo_banquito
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    container_name: sistema_banquito
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/banquito_caja
volumes:
  mongo_data: 